services:
  # O serviço de banco local foi removido/comentado pois estamos usando Aiven (Postgres Nuvem)
  
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: central-transfers-api
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}

  frontend:
    build:
      context: .
      dockerfile: painel-saas/Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:8001}
        - VITE_VAPID_PUBLIC_KEY=${VITE_VAPID_PUBLIC_KEY}
    container_name: central-transfers-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    env_file:
      - .env