app = "central-transfers-backend"
primary_region = "iad"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["http"]

  [services.concurrency]
    type = "requests"
    soft_limit = 20
    hard_limit = 25

  [services.http_checks]
    path = "/"
    interval = "10s"
    timeout = "2s"
    healthy_threshold = 2
    unhealthy_threshold = 2
