"""init_clean

Revision ID: 425a75d6ae6d
Revises: 
Create Date: 2026-05-11 21:48:43.283559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '425a75d6ae6d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clientes'))
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_id'), ['id'], unique=False)

    op.create_table('motoristas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('carro', sa.String(), nullable=True),
    sa.Column('placa', sa.String(), nullable=True),
    sa.Column('modelo', sa.String(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('comissao_master', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('ultima_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('plano', sa.String(), nullable=True),
    sa.Column('mensalidade_ativa', sa.Boolean(), nullable=True),
    sa.Column('vencimento_mensalidade', sa.DateTime(), nullable=True),
    sa.Column('data_inicio_trial', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_motoristas')),
    sa.UniqueConstraint('email', name=op.f('uq_motoristas_email'))
    )
    with op.batch_alter_table('motoristas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_motoristas_id'), ['id'], unique=False)

    op.create_table('servicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_servicos'))
    )
    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servicos_id'), ['id'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios'))
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_id'), ['id'], unique=False)

    op.create_table('mensalidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=True),
    sa.Column('mes_referencia', sa.String(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('data_pagamento', sa.DateTime(), nullable=True),
    sa.Column('checkout_url', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], name=op.f('fk_mensalidades_motorista_id_motoristas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mensalidades'))
    )
    with op.batch_alter_table('mensalidades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mensalidades_id'), ['id'], unique=False)

    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('servico_id', sa.Integer(), nullable=True),
    sa.Column('motorista_id', sa.Integer(), nullable=True),
    sa.Column('origem', sa.String(), nullable=False),
    sa.Column('destino', sa.String(), nullable=False),
    sa.Column('data_servico', sa.DateTime(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_comissao', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_liquido_motorista', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('comissao', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('canal_venda', sa.String(), nullable=True),
    sa.Column('tipo_comissao_motorista', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('fk_pedidos_cliente_id_clientes')),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], name=op.f('fk_pedidos_motorista_id_motoristas')),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], name=op.f('fk_pedidos_servico_id_servicos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pedidos'))
    )
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedidos_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedidos_id'))

    op.drop_table('pedidos')
    with op.batch_alter_table('mensalidades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mensalidades_id'))

    op.drop_table('mensalidades')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servicos_id'))

    op.drop_table('servicos')
    with op.batch_alter_table('motoristas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_motoristas_id'))

    op.drop_table('motoristas')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_id'))

    op.drop_table('clientes')
    # ### end Alembic commands ###
