"""add_categoria_servicos

Revision ID: a0818ce1c9d0
Revises: add_push_token_motoristas
Create Date: 2026-05-21 19:04:26.416133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0818ce1c9d0'
down_revision: Union[str, Sequence[str], None] = 'add_push_token_motoristas'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motoristas', schema=None) as batch_op:
        batch_op.drop_column('push_subscription')

    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('valor_padrao', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('capacidade_passageiros', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('capacidade_malas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('imagem_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.drop_column('imagem_url')
        batch_op.drop_column('capacidade_malas')
        batch_op.drop_column('capacidade_passageiros')
        batch_op.drop_column('valor_padrao')
        batch_op.drop_column('categoria')

    with op.batch_alter_table('motoristas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('push_subscription', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
